# server port 번호 설정
server:
  port: 8989

# data base 연동 설정
spring:
  datasource:
    #mariadb는 자신이 사용하고자 하는 스키마를 입력해야지 들어가짐.
    url: jdbc:mariadb://localhost:3306/sample3
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  # thymeleaf 캐시 설정
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: update

# db query log 관련 설정
logging:
  level:
    org:
      hibernate:
        SQL: trace
        type:
          descriptor:
            sql:
              BasicBinder: trace