spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/shop
    username: root
    password: hkit301301
    driver-class-name: org.mariadb.jdbc.Driver

mail:
  username:
  password:

#  mail:
#    host: smtp.naver.com
#    port: 465
#    username:
#    password:
#    properties:
#      mail.transport.protocol: smtp
#      mail.smtp.auth: true
#      mail.smtp.starttls.enable: ture
#      mail.debug: true
#      mail.smtp.ssl.enable: true
#      mail.smtp.ssl.trust: smtp.naver.com